config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
metadata:
  site_url: 'https://halide.netlify.app'
  site_title: Meghan Purkiss
  site_subtitle_1: Art Director
  site_subtitle_2: Marketing & Events
  site_description: |
    Meghan is an accomplished Senior Art Director and Graphic Designer with a strong background in marketing and events. She is proficient in industry-leading tools such as Adobe Illustrator, Photoshop, InDesign, and XD. Meghan specializse in print design, package design, logos, 3D modeling in Sketchup, and crafting engaging event materials for both virtual and in-person experiences.

    As an Art Director, she brings a strategic eye to design, ensuring a cohesive visual narrative. Meghan is experienced in website design and creating impactful presentation decks for client proofs, RFPs and events.
  site_email: ''
  site_social_url: 'https://www.linkedin.com/in/meghanpurkiss/'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Halide - Jamstack portfolio theme
    site_description: 'A customizable, minimalist portfolio website designed for photographers and still image creators.'
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: false
    item_output_limit: 48
    transition_duration: 300
    show_project_year: false
    show_project_grid_titles: true
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: GitHub
